community.suse.com blog posts
fuseml/wiki pull request #4
Opened 2021-07-15 09:24 UTC by stefannica

2021-07-15 13:03 UTC, flaviodsr commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +With the hype of AI on the rise, organizations have been investing more and more in Machine Learning to make better and faster business decisions or to automate key aspects of their operations or pro
I am not sure about the correct form to say hype (`hype of`, `hype for`, both?). Maybe the same could also be write like this? `With the AI hype on the rise...`

In `...decisions or to automate key aspects of their operations or production processes` this double `or` sounds confusing to me, maybe the second `or` could be replace by `and`?

Same here with the double `as`: `... as more than 80% of AI projects are failing to deliver business outcomes, as reported by Gartner in 2019 and repeatedly confirmed...` maybe that could be rephrased to remove one of them.

2021-07-15 14:44 UTC, stefannica commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +With the hype of AI on the rise, organizations have been investing more and more in Machine Learning to make better and faster business decisions or to automate key aspects of their operations or pro
done, done and done :)

2021-07-16 14:17 UTC, flaviodsr requested changes
Just a couple of suggestions.

Besides, I am not sure about the formality level of the blog post, but a I see a lot contractions which should not be used in formal texts.

Regarding the content I think it looks awesome. I wish I had read such article some months ago. I really liked it 👏

2021-07-16 14:17 UTC, flaviodsr commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +Naturally, following this realization about the challenges of using Machine Learning in production, a lot of effort went into investigating the whys and whats about this state of affairs. Today, we c
Instead of `"...we can say not only that the main causes for this..."`, maybe `"...we can not only say that the main causes for this..."` sounds better?

In `"...engineering discipline - MLOps - was created to..."` maybe `- Machine Learning Operations (MLOps) -` as this is the first time you are using the acronym.

2021-07-16 14:17 UTC, flaviodsr commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +The SUSE AI/ML team is thrilled to announce the official launch of [FuseML](https://fuseml.github.io), an Open Source orchestration framework for MLOps. FuseML brings a novel holistic interpretation
In `"...frictionless interaction of all roles involved..."`, maybe `...frictionless interaction between all roles involved..."`

2021-07-16 14:17 UTC, flaviodsr commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +MLOps ideas can be traced back all the way to the defining characteristics of Machine Learning. Before diving into MLOps, it will be insightful to make a detour and revisit what differentiates Machin
`...it will be insightful to...`, maybe `...it might be insightful to...`

2021-07-16 15:59 UTC, stefannica commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +MLOps ideas can be traced back all the way to the defining characteristics of Machine Learning. Before diving into MLOps, it will be insightful to make a detour and revisit what differentiates Machin
I thought about using the second one too. Both sound a bit weird. I'll explore some alternatives...

2021-07-16 18:52 UTC, stefannica commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +Naturally, following this realization about the challenges of using Machine Learning in production, a lot of effort went into investigating the whys and whats about this state of affairs. Today, we c
done

2021-07-16 18:52 UTC, stefannica commented on articles/community.suse.com/fuseml-mlops-episode-one.md
> +The SUSE AI/ML team is thrilled to announce the official launch of [FuseML](https://fuseml.github.io), an Open Source orchestration framework for MLOps. FuseML brings a novel holistic interpretation
done

2021-07-19 08:27 UTC, flaviodsr approved these changes

2021-07-19 09:30 UTC, merged